Repository 2024-TEAM-05/integrated-feed-backend, pull requests merged in 2024-08, with the labels that each got.

#4 Initial project structure setup
  .gitignore
  .idea/.gitignore
  build.gradle
  gradlew
  gradlew.bat
  src/main/java/team05/integrated_feed_backend/IntegratedFeedBackendApplication.java
  src/main/java/team05/integrated_feed_backend/common/annotation/.gitkeep
  src/main/java/team05/integrated_feed_backend/common/resolver/.gitkeep
  src/main/java/team05/integrated_feed_backend/common/util/.gitkeep
  src/main/java/team05/integrated_feed_backend/core/config/.gitkeep
  src/main/java/team05/integrated_feed_backend/core/properties/.gitkeep
  src/main/java/team05/integrated_feed_backend/exception/custom/.gitkeep
  src/main/java/team05/integrated_feed_backend/exception/dto/.gitkeep
  src/main/java/team05/integrated_feed_backend/infra/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/auth/controller/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/auth/dto/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/auth/repository/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/auth/service/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/controller/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/dto/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/entity/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/repository/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/service/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/controller/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/dto/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/entity/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/repository/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/service/.gitkeep
  src/main/resources/application.yml
  src/test/java/team05/integrated_feed_backend/IntegratedFeedBackendApplicationTests.java
Labels: 💫 enhancement

#8 feat: swagger 설정
  build.gradle
  src/main/java/team05/integrated_feed_backend/core/config/SwaggerConfig.java
Labels: 💫 enhancement

#13 chore: CI 파이프라인 작성
  .github/workflows/ci-pipeline.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/resources/application-template.yml
  src/test/resources/application-test.yml
Labels: 💫 enhancement

#19 feat: QueryDSL 설정
  .gitignore
  build.gradle
  src/main/java/team05/integrated_feed_backend/core/config/QueryDSLConfig.java
Labels: 💫 enhancement

#17 docs: README.md 수정
  README.md
Labels: 📃 documentation

#9 feat: error handling & ApiResponse 추가
  src/main/java/team05/integrated_feed_backend/common/BaseApiResponse.java
  src/main/java/team05/integrated_feed_backend/exception/GlobalExceptionHandler.java
  src/main/java/team05/integrated_feed_backend/exception/code/StatusCode.java
  src/main/java/team05/integrated_feed_backend/exception/custom/BadRequestException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/BusinessException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/DataNotFoundException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/DuplicateResourceException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/ForbiddenException.java
Labels: 💫 enhancement

#24 feat: 좋아요, 공유수 api infra 계층 작성
  .gitignore
  build.gradle
  src/main/java/team05/integrated_feed_backend/IntegratedFeedBackendApplication.java
  src/main/java/team05/integrated_feed_backend/core/config/.gitkeep
  src/main/java/team05/integrated_feed_backend/core/config/FeignConfig.java
  src/main/java/team05/integrated_feed_backend/infra/sns/adapter/FacebookAdapter.java
  src/main/java/team05/integrated_feed_backend/infra/sns/adapter/InstagramAdapter.java
  src/main/java/team05/integrated_feed_backend/infra/sns/adapter/ThreadsAdapter.java
  src/main/java/team05/integrated_feed_backend/infra/sns/adapter/TwitterAdapter.java
  src/main/java/team05/integrated_feed_backend/infra/sns/api/FacebookApi.java
  src/main/java/team05/integrated_feed_backend/infra/sns/api/InstagramApi.java
  src/main/java/team05/integrated_feed_backend/infra/sns/api/ThreadApi.java
  src/main/java/team05/integrated_feed_backend/infra/sns/api/TwitterApi.java
Labels: 💫 enhancement

#25 feat: 게시판 목록 api 컨트롤러 계층 구현
  src/main/java/team05/integrated_feed_backend/common/dto/PaginationMetadata.java
  src/main/java/team05/integrated_feed_backend/common/dto/PaginationQuery.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostControllerDocs.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/dto/HashtagDto.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/PostDto.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/request/PostSearchReq.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostSearchRes.java
Labels: 💫 enhancement

#29 feat: 회원가입 Swagger 및 컨트롤러 작성
  .gitignore
  build.gradle
  src/main/java/team05/integrated_feed_backend/common/BaseApiResponse.java
  src/main/java/team05/integrated_feed_backend/common/code/StatusCode.java
  src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
  src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
  src/main/java/team05/integrated_feed_backend/module/user/controller/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/controller/MemberController.java
  src/main/java/team05/integrated_feed_backend/module/user/controller/MemberControllerDocs.java
  src/main/java/team05/integrated_feed_backend/module/user/dto/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/dto/request/MemberSignupReq.java
  src/main/java/team05/integrated_feed_backend/module/user/entity/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/service/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/user/service/MemberService.java
  src/main/resources/application-template.yml
  src/test/resources/application.yml
Labels: 📃 documentation, 💫 enhancement

#30 feat: 통계 조회 api dto, controller 계층 구현
  src/main/java/team05/integrated_feed_backend/common/util/DateTimeParser.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostStatisticsController.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostStatisticsControllerDocs.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/request/PostStatisticsListReq.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostStatisticsListRes.java
  src/main/java/team05/integrated_feed_backend/module/post/service/PostStatisticsService.java
Labels: 💫 enhancement

#32 feat: 게시물 좋아요, 공유 수 올리는 service, controller 계층 구현
  src/main/java/team05/integrated_feed_backend/IntegratedFeedBackendApplication.java
  src/main/java/team05/integrated_feed_backend/common/code/StatusCode.java
  src/main/java/team05/integrated_feed_backend/exception/GlobalExceptionHandler.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostControllerDocs.java
  src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
  src/main/java/team05/integrated_feed_backend/module/post/event/LikeCountIncreasedEvent.java
  src/main/java/team05/integrated_feed_backend/module/post/event/ShareCountIncreasedEvent.java
  src/main/java/team05/integrated_feed_backend/module/post/event/listener/PostEventListener.java
  src/main/java/team05/integrated_feed_backend/module/post/event/publisher/PostEventPublisher.java
  src/main/java/team05/integrated_feed_backend/module/post/repository/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/repository/PostRepository.java
  src/main/java/team05/integrated_feed_backend/module/post/service/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/service/PostService.java
  src/test/java/team05/integrated_feed_backend/MockEntityFactory.java
  src/test/java/team05/integrated_feed_backend/post/PostEventListenerTest.java
  src/test/java/team05/integrated_feed_backend/post/PostEventPublisherTest.java
  src/test/java/team05/integrated_feed_backend/post/PostServiceTest.java
Labels: 💫 enhancement

#36 feat: 게시물 목록 api 서비스, 리포지토리 작성
  .gitignore
  src/main/java/team05/integrated_feed_backend/common/dto/PaginationMetadata.java
  src/main/java/team05/integrated_feed_backend/common/dto/PaginationQuery.java
  src/main/java/team05/integrated_feed_backend/common/enums/OrderType.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/HashtagDto.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/PostDto.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/request/PostSearchReq.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostSearchRes.java
  src/main/java/team05/integrated_feed_backend/module/post/entity/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/post/entity/Hashtag.java
  src/main/java/team05/integrated_feed_backend/module/post/repository/PostCustomRepository.java
  src/main/java/team05/integrated_feed_backend/module/post/repository/PostCustomRepositoryImpl.java
  src/main/java/team05/integrated_feed_backend/module/post/repository/PostRepository.java
  src/main/java/team05/integrated_feed_backend/module/post/service/PostService.java
  src/test/java/team05/integrated_feed_backend/post/PostServiceTest.java
  src/test/java/team05/integrated_feed_backend/post/repository/PostRepositoryTest.java
Labels: 💫 enhancement

#35 feat: 게시물 상세 api 구현
  README.md
  src/main/java/team05/integrated_feed_backend/common/BaseApiResponse.java
  src/main/java/team05/integrated_feed_backend/common/code/StatusCode.java
  src/main/java/team05/integrated_feed_backend/common/util/ValidationUtil.java
  src/main/java/team05/integrated_feed_backend/exception/GlobalExceptionHandler.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostController.java
  src/main/java/team05/integrated_feed_backend/module/post/controller/PostControllerDocs.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/response/HashtagDto.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDetailRes.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostDto.java
  src/main/java/team05/integrated_feed_backend/module/post/dto/response/PostSearchRes.java
  src/main/java/team05/integrated_feed_backend/module/post/entity/Post.java
  src/main/java/team05/integrated_feed_backend/module/post/repository/PostRepository.java
  src/main/java/team05/integrated_feed_backend/module/post/service/PostMapper.java
  src/main/java/team05/integrated_feed_backend/module/post/service/PostService.java
  src/test/java/team05/integrated_feed_backend/module/post/service/PostServiceGetPostDetailTest.java
Labels: 📃 documentation, 💫 enhancement

#34 feat: 회원가입 비즈니스 로직 구현
  build.gradle
  src/main/java/team05/integrated_feed_backend/common/code/StatusCode.java
  src/main/java/team05/integrated_feed_backend/common/util/VerificationCodeGenerator.java
  src/main/java/team05/integrated_feed_backend/core/config/SecurityConfig.java
  src/main/java/team05/integrated_feed_backend/exception/custom/BadRequestException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/BusinessException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/DataNotFoundException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/DuplicateResourceException.java
  src/main/java/team05/integrated_feed_backend/exception/custom/ForbiddenException.java
  src/main/java/team05/integrated_feed_backend/infra/mail/MailService.java
  src/main/java/team05/integrated_feed_backend/infra/mail/SimpleMailService.java
  src/main/java/team05/integrated_feed_backend/module/auth/entity/VerificationCode.java
  src/main/java/team05/integrated_feed_backend/module/auth/repository/VerificationCodeRepository.java
  src/main/java/team05/integrated_feed_backend/module/member/controller/MemberController.java
  src/main/java/team05/integrated_feed_backend/module/member/controller/MemberControllerDocs.java
  src/main/java/team05/integrated_feed_backend/module/member/dto/request/MemberSignupReq.java
  src/main/java/team05/integrated_feed_backend/module/member/entity/Member.java
  src/main/java/team05/integrated_feed_backend/module/member/entity/enums/MemberStatus.java
  src/main/java/team05/integrated_feed_backend/module/member/entity/vo/Email.java
  src/main/java/team05/integrated_feed_backend/module/member/entity/vo/Password.java
  src/main/java/team05/integrated_feed_backend/module/member/event/SignedUpEvent.java
  src/main/java/team05/integrated_feed_backend/module/member/event/listener/MemberEventListener.java
  src/main/java/team05/integrated_feed_backend/module/member/event/publisher/MemberEventPublisher.java
  src/main/java/team05/integrated_feed_backend/module/member/repository/.gitkeep
  src/main/java/team05/integrated_feed_backend/module/member/repository/MemberRepository.java
  src/main/java/team05/integrated_feed_backend/module/member/service/MemberService.java
  src/main/java/team05/integrated_feed_backend/module/user/service/MemberService.java
  src/test/java/team05/integrated_feed_backend/module/member/entity/vo/EmailTest.java
  src/test/java/team05/integrated_feed_backend/module/member/entity/vo/PasswordTest.java
Labels: 💫 enhancement

#54 리드미에 회원가입 테크 스펙 추가
  README.md
Labels: 📃 documentation
